apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go
  replicas: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go-app
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }} # name of Docker Hub ID
          IMAGE_NAME: docker-gs-ping
          IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
        image: $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        ports:
        - containerPort: 8082
