apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go
  replicas: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go-app
        image: 2devops3/docker-gs-ping:dev-5e06c36
        ports:
        - containerPort: 8082
