name: Go Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }} # name of Docker Hub ID
      IMAGE_NAME: docker-gs-ping
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

    - name: Docker Push
      run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
      
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.2
      with:
        files: '["*.yaml"]'
        tokenPrefix: '__' # optional, default is #{
        tokenSuffix: '__' # optional, default is }#
      env:
        DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
    
    - name: Run Kube-Bench to check cluster config
      continue-on-error: true
      run: |
        kubectl apply -f https://github.com/1DevOps2/docker-gs-ping/blob/main/deployment.yaml
        
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
#     - name: Update image tag in manifest
#       run: |
#         sed -i 's|image: 2devops3/docker-gs-ping:v\.|image: 2devops3/docker-gs-ping:v.${{ github.run_number }}|g' ${{ github.workspace }}/deployment.yaml

        

    
#     - name: Publish the Docker image
#       uses: docker/build-push-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: 2devops3/go-app
#         tags: 0.2
