name: Go Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t 2devops3/go-app .
      
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ github.run_id }}
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/docker-gs-ping:$IMAGE_TAG

    - name: Docker Push
      env:
        IMAGE_TAG: ${{ github.run_id }}
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-gs-ping:$IMAGE_TAG

#     - name: Publish the Docker image
#       uses: docker/build-push-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: 2devops3/go-app
#         tags: 0.2
